### ISSUE TITLE
about experiment set

### ISSUE THREAD

**Issue by LuckyDush** [AIR-THU/V2X-Graph#1]
![image](https://github.com/AIR-THU/V2X-Graph/assets/95169135/89567b4e-ebec-45ef-bde3-e00730e5d6b7)
![image](https://github.com/AIR-THU/V2X-Graph/assets/95169135/76325556-b1da-4b01-8af4-1fc49663b7ad)
![image](https://github.com/AIR-THU/V2X-Graph/assets/95169135/2660f79e-7346-444d-9432-2eb3f0fd9938)
您好，很棒的工作，有一些细节想要了解一下，请问论文中PPVIC和V2X-Graph测试是在50000协同数据中的自车下测试的吗？PP-VIC在V2X-graph中的效果要比在V2X-seq效果好很多，是更改了什么设置吗？还是只是将V2X-seq中的CBMOT融合数据上的测试换成了协同数据中的自车下测试效果就会变好吗？

**Comment by HzRynn** [comment]
您好，实验结果是以V2X-Seq开源为准[https://github.com/AIR-THU/DAIR-V2X-Seq/tree/main/docs/benchmarks/vic-traj-forecasting](url)，测试都是以协同数据中自车数据的gt来评估
